# -*- coding: utf-8 -*-
"""
SINGLE SOURCE OF TRUTH for the crawlable subpages' content (services / projects /
profile / classes / hubs), trilingual es+en+ru. Grounded in inga_kb (services,
pricing, real projects Habanero / Boca Pez / panel / firebird, bio, classes).

  * Edit THIS file to change subpage content, add a page, or add a language string.
  * `build.sh` runs this script automatically, so `pages.json` is a GENERATED
    artifact — do NOT hand-edit pages.json (it gets overwritten on every build).
  * Run standalone to preview:  python3 web/pages.gen.py   (rewrites web/pages.json)

Field reference (per page dict):
  id        unique slug id (used for parent/children/related refs)
  kind      "service" | "project" | "profile" | "hub"  (chooses the renderer)
  parent    id of the hub for the breadcrumb (omit for top-level pages)
  img       hero image TOKEN (must exist in build.sh MAP), also the OG preview
  path      {es,en,ru} FULL localized url path, NO leading/trailing slash;
            es has no prefix, en starts "en/…", ru starts "ru/…"
  crumb/h1/title/desc/snippet   localized {es,en,ru} strings (title = <title>,
            desc = meta description, snippet = promptable answer-first lead)
            ⚠ KEEP EACH `desc` ≤ 160 CHARACTERS (Bing/Google truncate longer; Bing
            Webmaster flags them). Home meta.description lives in i18n.json, same limit.
  serviceType   (service) English service type for JSON-LD
  intro/includes/faq/price      (service) localized bodies; faq = list of [q,a]
  meta_line/story/details/gallery/artwork   (project) localized bodies + facts
  paras     (profile) localized list of bio paragraphs
  children  (hub) list of child page ids to render as cards
  gallery   list of {img: TOKEN, alt:{es,en,ru}}
  related   list of page ids linked at the foot of the page
  eyebrow/card/*_title   optional localized overrides
See build.sh (RENDER dict, page_entity, KIND_EYE) for how each field is used.
"""
import json, pathlib

def tri(es, en, ru): return {"es": es, "en": en, "ru": ru}
def tri_list(es, en, ru): return {"es": es, "en": en, "ru": ru}

pages = []

# ---------------------------------------------------------------- HUB: servicios
pages.append({
  "id": "servicios", "kind": "hub", "img": "SRC_CASE2",
  "path": tri("servicios", "en/services", "ru/uslugi"),
  "crumb": tri("Servicios", "Services", "Услуги"),
  "h1": tri("Servicios de arte cerámico a medida",
            "Custom ceramic art services",
            "Услуги авторского керамического искусства"),
  "title": tri("Servicios — murales, paneles y vajilla cerámica a medida | IngArt Studio",
               "Services — custom ceramic murals, panels and tableware | IngArt Studio",
               "Услуги — керамические муралы, панно и посуда на заказ | IngArt Studio"),
  "desc": tri("Murales y paneles cerámicos a medida, vajilla de autor para restaurantes y decoración cerámica en Benicàssim y Castellón. Desde el boceto al montaje.",
              "Custom ceramic murals and panels, tableware for restaurants and ceramic decoration in Benicàssim and Castellón. From sketch to installation.",
              "Керамические муралы и панно на заказ, авторская посуда для ресторанов и керамический декор в Benicàssim и Castellón. От эскиза до монтажа."),
  "snippet": tri("Cuatro maneras de llevar la cerámica de autor a tu espacio — del panel para una vivienda al mural de un restaurante, de la vajilla a medida a la decoración cerámica completa. Todo diseñado, producido e instalado por Inga Burina, del boceto al montaje.",
                 "Four ways to bring artistic ceramics into your space — from a panel for a home to a restaurant mural, from bespoke tableware to full ceramic decoration. All designed, produced and installed by Inga Burina, from sketch to installation.",
                 "Четыре способа привести авторскую керамику в ваше пространство — от панно для дома до мурала в ресторане, от посуды на заказ до полного керамического декора. Всё создаёт и монтирует Инга Бурина — от эскиза до монтажа."),
  "children": ["murales-ceramicos", "paneles-vivienda", "vajilla-restaurantes", "decoracion-espacios"],
})

# ---------------------------------------------------------------- HUB: proyectos
pages.append({
  "id": "proyectos", "kind": "hub", "img": "SRC_GORY_ROOM",
  "path": tri("proyectos", "en/projects", "ru/proekty"),
  "crumb": tri("Proyectos", "Projects", "Проекты"),
  "h1": tri("Proyectos de cerámica artística",
            "Ceramic art projects",
            "Проекты авторской керамики"),
  "title": tri("Proyectos — murales, paneles y vajilla cerámica | IngArt Studio",
               "Projects — ceramic murals, panels and tableware | IngArt Studio",
               "Проекты — керамические муралы, панно и посуда | IngArt Studio"),
  "desc": tri("Proyectos de Inga Burina: un panel cerámico para una vivienda en Castellón, el mural de selva del restaurante Habanero y vajilla a medida para Boca Pez.",
              "Inga Burina's projects: a ceramic panel for a home in Castellón, the jungle mural at Habanero restaurant and bespoke tableware for Boca Pez.",
              "Проекты Инги Буриной: керамическое панно для дома в Castellón, мурал «джунгли» в ресторане Habanero и посуда на заказ для Boca Pez."),
  "snippet": tri("Cada proyecto se crea de nuevo, para un espacio y unas personas concretas. Estos son algunos de los encargos — viviendas privadas y restaurantes de la costa de Castellón — con la idea, los materiales y el resultado.",
                 "Every project is created from scratch, for a specific space and specific people. Here are some of the commissions — private homes and restaurants along the Castellón coast — with the idea, the materials and the result.",
                 "Каждый проект создаётся заново — под конкретное пространство и конкретных людей. Вот несколько заказов — частные дома и рестораны побережья Castellón — с идеей, материалами и результатом."),
  "children": ["panel-montanas", "mural-habanero", "vajilla-boca-pez", "ave-fuego"],
})

# ---------------------------------------------------- SERVICE: murales cerámicos
pages.append({
  "id": "murales-ceramicos", "kind": "service", "parent": "servicios", "img": "SRC_CASE2",
  "serviceType": "Custom ceramic murals",
  "path": tri("servicios/murales-ceramicos-a-medida",
              "en/services/custom-ceramic-murals",
              "ru/uslugi/keramicheskie-murali-na-zakaz"),
  "crumb": tri("Murales cerámicos a medida", "Custom ceramic murals", "Керамические муралы на заказ"),
  "card": tri("Grandes murales de azulejo pintado a mano para restaurantes, hoteles y viviendas.",
              "Large hand-painted tile murals for restaurants, hotels and homes.",
              "Большие муралы из расписной плитки для ресторанов, отелей и домов."),
  "h1": tri("Murales cerámicos a medida en Benicàssim y Castellón",
            "Custom ceramic murals in Benicàssim and Castellón",
            "Керамические муралы на заказ в Benicàssim и Castellón"),
  "title": tri("Murales cerámicos a medida en Benicàssim | Inga Burina",
               "Custom ceramic murals in Benicàssim | Inga Burina",
               "Керамические муралы на заказ в Benicàssim | Инга Бурина"),
  "desc": tri("Artista en Benicàssim especializada en murales cerámicos a medida para restaurantes, hoteles y viviendas en Castellón. Azulejo pintado a mano, desde 200 €/m².",
              "Benicàssim artist making custom ceramic murals for restaurants, hotels and homes in Castellón. Hand-painted tile, design to install, from 200 €/m².",
              "Художница из Benicàssim: керамические муралы на заказ для ресторанов, отелей и домов в Castellón. Расписная плитка, от эскиза до монтажа, от 200 €/м²."),
  "img_alt": tri("Mural cerámico de selva pintado a mano en el restaurante Habanero, Benicàssim",
                 "Hand-painted ceramic jungle mural at Habanero restaurant, Benicàssim",
                 "Расписной керамический мурал «джунгли» в ресторане Habanero, Benicàssim"),
  "snippet": tri("Diseño y realizo murales cerámicos a medida — azulejo pintado a mano y composiciones a gran escala — que convierten una pared en el corazón de un restaurante, un hotel o una vivienda. Cada mural nace del concepto del espacio y de la naturaleza mediterránea, del primer boceto al montaje in situ.",
                 "I design and make custom ceramic murals — hand-painted tile and large-scale compositions — that turn a wall into the heart of a restaurant, a hotel or a home. Each mural grows from the concept of the space and the Mediterranean nature, from the first sketch to the on-site installation.",
                 "Проектирую и создаю керамические муралы на заказ — расписную плитку и крупные композиции, — которые превращают стену в сердце ресторана, отеля или дома. Каждый мурал рождается из концепции пространства и средиземноморской природы — от первого эскиза до монтажа на месте."),
  "intro": tri_list(
    ["Un mural cerámico no es un cuadro colgado: forma parte de la arquitectura. El azulejo pintado a mano y esmaltado a fuego aporta textura, profundidad y color que perduran, en interior y en exterior. Es una superficie que se toca, que cambia con la luz y que da carácter a todo el espacio.",
     "Trabajo el mural como una escena de autor pensada para tu lugar: la fauna tropical de un restaurante, la costa rocosa de una vivienda, un motivo ligado a la marca. Nada de copiar referencias de internet — una idea propia, adaptada a tu espacio y a tu luz."],
    ["A ceramic mural is not a hung picture: it becomes part of the architecture. Hand-painted, kiln-fired tile brings texture, depth and colour that last, indoors and outdoors. It is a surface you can touch, that shifts with the light and gives character to the whole space.",
     "I treat the mural as an authored scene made for your place: the tropical fauna of a restaurant, the rocky coast of a home, a motif tied to a brand. No copying references from the internet — an original idea, adapted to your space and your light."],
    ["Керамический мурал — не картина на стене: он становится частью архитектуры. Расписная обожжённая плитка даёт фактуру, глубину и цвет, которые не выцветают — внутри и снаружи. Это поверхность, к которой хочется прикоснуться, которая играет со светом и задаёт характер всему пространству.",
     "Мурал я делаю как авторскую сцену под ваше место: тропическая фауна ресторана, скалистый берег для дома, мотив, связанный с брендом. Никаких копий с референсов из интернета — собственная идея, адаптированная под ваше пространство и свет."]),
  "includes": tri_list(
    ["Concepto artístico y bocetos pensados para tu espacio",
     "Azulejo cerámico pintado a mano y esmaltado a fuego",
     "Pruebas de esmaltes, texturas y muestras de material",
     "Cálculo de materiales y presupuesto cerrado",
     "Producción modular en el estudio",
     "Montaje in situ con equipo técnico (electricistas, alicatadores)"],
    ["Artistic concept and sketches designed for your space",
     "Hand-painted, kiln-fired ceramic tile",
     "Glaze, texture and material samples",
     "Material calculation and a closed budget",
     "Modular production in the studio",
     "On-site installation with a technical team (electricians, tilers)"],
    ["Художественная концепция и эскизы под ваше пространство",
     "Расписная керамическая плитка, обожжённая в печи",
     "Пробы глазурей, фактур и образцы материалов",
     "Расчёт материалов и фиксированная смета",
     "Модульное производство в студии",
     "Монтаж на месте с технической командой (электрики, плиточники)"]),
  "price": tri("Obra artística desde 200 €/m², materiales aparte. Bocetos 150–300 € según el proyecto; después, anticipo. Cerámica para interior y exterior — material perdurable, con garantía.",
               "Artwork from 200 €/m², materials separate. Sketches 150–300 € depending on the project; then a deposit. Ceramics for indoor and outdoor use — a lasting material, with warranty.",
               "Художественная работа от 200 €/м², материалы отдельно. Эскизы 150–300 € в зависимости от проекта, далее предоплата. Керамика для интерьера и экстерьера — долговечный материал, с гарантией."),
  "gallery": [
    {"img": "SRC_FEATURE", "alt": tri("Tríptico cerámico de selva con monos y aves tropicales para el restaurante Habanero",
                                       "Ceramic jungle triptych with monkeys and tropical birds for Habanero restaurant",
                                       "Керамический триптих «джунгли» с обезьянами и тропическими птицами для ресторана Habanero")},
    {"img": "SRC_PROCESS", "alt": tri("Inga Burina pintando a mano el azulejo cerámico del mural en el estudio",
                                       "Inga Burina hand-painting the mural's ceramic tile in the studio",
                                       "Инга Бурина расписывает вручную керамическую плитку мурала в студии")},
    {"img": "SRC_GORY_ROOM", "alt": tri("Panel cerámico a medida instalado en una terraza con vistas al mar",
                                         "Custom ceramic panel installed on a terrace with sea views",
                                         "Керамическое панно на заказ, установленное на террасе с видом на море")},
  ],
  "faq": tri_list(
    [["¿Se puede instalar un mural cerámico en el exterior?",
      "Sí. La cerámica esmaltada es un material perdurable, apto para interior y exterior — fachadas, patios, terrazas y zonas húmedas. Se entrega con garantía cuando se respetan las condiciones de instalación."],
     ["¿Cuánto tarda un mural?",
      "Entre 1 mes y varios meses según el tamaño y el detalle. La cerámica se produce por módulos en el estudio y se monta después in situ, lo que permite planificar la obra con precisión."],
     ["¿Trabajáis con arquitectos e interioristas?",
      "Sí, es lo habitual. Puedo entrar en la fase de planificación de la reforma o crear una atmósfera nueva en un espacio ya terminado. Aporto bocetos, muestras y, si hace falta, visualizaciones."]],
    [["Can a ceramic mural be installed outdoors?",
      "Yes. Glazed ceramic is a lasting material, suitable indoors and outdoors — façades, patios, terraces and wet areas. It comes with a warranty when installation conditions are met."],
     ["How long does a mural take?",
      "From 1 month to several, depending on size and detail. The ceramic is produced in modules in the studio and installed on site afterwards, which allows the work to be planned precisely."],
     ["Do you work with architects and interior designers?",
      "Yes, routinely. I can join at the renovation planning stage or create a new atmosphere in an already finished space. I provide sketches, samples and, if needed, visualisations."]],
    [["Можно ли установить керамический мурал снаружи?",
      "Да. Глазурованная керамика — долговечный материал, подходит для интерьера и экстерьера: фасады, патио, террасы, влажные зоны. Даётся гарантия при соблюдении условий монтажа."],
     ["Сколько делается мурал?",
      "От 1 месяца до нескольких — зависит от размера и детализации. Керамика производится модулями в студии, а затем монтируется на месте, что позволяет точно планировать работы."],
     ["Работаете ли с архитекторами и дизайнерами?",
      "Да, это обычная практика. Могу подключиться на стадии планирования ремонта или создать новую атмосферу в уже готовом пространстве. Даю эскизы, образцы и при необходимости визуализации."]]),
  "related": ["paneles-vivienda", "mural-habanero", "decoracion-espacios"],
})

# ------------------------------------------------- SERVICE: paneles para vivienda
pages.append({
  "id": "paneles-vivienda", "kind": "service", "parent": "servicios", "img": "SRC_CASE1",
  "serviceType": "Custom ceramic panels for homes",
  "path": tri("servicios/paneles-ceramicos-para-vivienda",
              "en/services/ceramic-panels-for-homes",
              "ru/uslugi/keramicheskie-panno-dlya-doma"),
  "crumb": tri("Paneles para vivienda", "Panels for homes", "Панно для дома"),
  "card": tri("Paneles cerámicos de pared a medida con motivos de la naturaleza mediterránea.",
              "Bespoke ceramic wall panels with Mediterranean nature motifs.",
              "Керамические панно на стену с мотивами средиземноморской природы."),
  "h1": tri("Paneles cerámicos a medida para viviendas",
            "Custom ceramic panels for homes",
            "Керамические панно на заказ для дома"),
  "title": tri("Paneles cerámicos a medida para viviendas | Inga Burina",
               "Custom ceramic panels for homes | Inga Burina",
               "Керамические панно на заказ для дома | Инга Бурина"),
  "desc": tri("Paneles cerámicos de pared a medida para viviendas en Castellón: motivos naturales pintados a mano, montaje modular. Del boceto al montaje, desde 200 €/m².",
              "Bespoke ceramic wall panels for homes in Castellón: hand-painted natural motifs, modular installation. From sketch to fitting, from 200 €/m².",
              "Керамические настенные панно на заказ для домов в Castellón: расписные природные мотивы, модульный монтаж. От эскиза до монтажа, от 200 €/м²."),
  "img_alt": tri("Panel cerámico con montañas, agaves y suculentas de la costa mediterránea en una vivienda",
                 "Ceramic panel with mountains, agaves and succulents of the Mediterranean coast in a home",
                 "Керамическое панно с горами, агавами и суккулентами средиземноморского берега в доме"),
  "snippet": tri("Un panel cerámico convierte una pared de casa en una obra que habla en voz baja: la costa rocosa, las suculentas, un ave al atardecer. Es el encargo que más disfruto — una pieza de autor pensada para tu hogar, su luz y su historia, del boceto al montaje.",
                 "A ceramic panel turns a home wall into a work that speaks softly: the rocky coast, the succulents, a bird at dusk. It is the commission I enjoy most — an authored piece made for your home, its light and its story, from sketch to installation.",
                 "Керамическое панно превращает стену дома в работу, которая говорит вполголоса: скалистый берег, суккуленты, птица на закате. Это заказ, который я люблю больше всего, — авторская вещь под ваш дом, его свет и историю, от эскиза до монтажа."),
  "intro": tri_list(
    ["Los paneles son el corazón de mi trabajo con viviendas particulares. Parto de lo que rodea la casa — el mar, las rocas, los agaves, la luz del atardecer — y lo llevo a la pared en cerámica pintada a mano, con una manera realista y a la vez decorativa.",
     "La cerámica es modular: el panel se produce por partes en el estudio y se monta en tu pared, lo que permite piezas grandes sin obra pesada. Sirve para el salón, la entrada, una terraza o una zona exterior, porque el material resiste el interior y el exterior."],
    ["Panels are the heart of my work with private homes. I start from what surrounds the house — the sea, the rocks, the agaves, the evening light — and bring it to the wall in hand-painted ceramic, in a way that is realistic and decorative at once.",
     "Ceramic is modular: the panel is produced in parts in the studio and mounted on your wall, which allows large pieces without heavy building work. It suits a living room, an entrance, a terrace or an outdoor area, because the material withstands both indoors and outdoors."],
    ["Панно — сердце моей работы с частными домами. Я отталкиваюсь от того, что окружает дом, — море, скалы, агавы, вечерний свет — и переношу это на стену в расписной керамике, в манере реалистичной и одновременно декоративной.",
     "Керамика модульна: панно производится по частям в студии и монтируется на вашей стене — это позволяет делать крупные вещи без тяжёлого ремонта. Подходит для гостиной, прихожей, террасы или наружной зоны, ведь материал выдерживает и интерьер, и экстерьер."]),
  "includes": tri_list(
    ["Visita o estudio del espacio a partir de fotos y medidas",
     "Concepto y bocetos ligados a tu entorno y tu luz",
     "Cerámica pintada a mano, modular",
     "Pruebas de esmaltes y muestras de color",
     "Presupuesto cerrado; materiales aparte",
     "Montaje in situ; posible montaje a distancia en proyectos lejanos"],
    ["A visit or a study of the space from photos and measurements",
     "Concept and sketches tied to your surroundings and light",
     "Hand-painted, modular ceramic",
     "Glaze and colour samples",
     "A closed budget; materials separate",
     "On-site installation; remote installation possible for distant projects"],
    ["Выезд или изучение пространства по фото и замерам",
     "Концепция и эскизы под ваше окружение и свет",
     "Расписная керамика, модульная",
     "Пробы глазурей и образцы цвета",
     "Фиксированная смета; материалы отдельно",
     "Монтаж на месте; для дальних проектов возможен дистанционный монтаж"]),
  "price": tri("Obra artística desde 200 €/m², materiales aparte. Bocetos 150–300 €. Plazos de 1 mes a varios según el tamaño. Cerámica para interior y exterior, con garantía.",
               "Artwork from 200 €/m², materials separate. Sketches 150–300 €. Timelines from 1 month to several depending on size. Ceramics for indoor and outdoor use, with warranty.",
               "Художественная работа от 200 €/м², материалы отдельно. Эскизы 150–300 €. Сроки от 1 месяца до нескольких в зависимости от размера. Керамика для интерьера и экстерьера, с гарантией."),
  "gallery": [
    {"img": "SRC_PANEL", "alt": tri("Panel cerámico de pared con suculentas pintadas a mano",
                                     "Ceramic wall panel with hand-painted succulents",
                                     "Керамическое настенное панно с расписанными вручную суккулентами")},
    {"img": "SRC_GORY_SUCC", "alt": tri("Detalle de panel: suculentas y agaves de la costa mediterránea",
                                         "Panel detail: succulents and agaves of the Mediterranean coast",
                                         "Фрагмент панно: суккуленты и агавы средиземноморского берега")},
    {"img": "SRC_GORY_BIRD", "alt": tri("Detalle de panel: abubilla en una rama de pino sobre el mar al atardecer",
                                         "Panel detail: hoopoe on a pine branch above the sea at dusk",
                                         "Фрагмент панно: удод на ветке сосны над морем на закате")},
  ],
  "faq": tri_list(
    [["¿Puedo encargar un panel solo con una idea?",
      "Sí. Puedes venir solo con una idea o incluso con una sensación. A partir de ahí me encargo del concepto, los bocetos, los cálculos y toda la realización."],
     ["¿De qué tamaño puede ser?",
      "Al ser modular, el panel puede ser pequeño o cubrir una pared entera. Se fabrica por partes en el estudio y se ensambla en tu casa."],
     ["¿Sirve para una terraza o un exterior?",
      "Sí. La cerámica esmaltada aguanta el sol, la humedad y el frío; es un material perdurable para interior y exterior, con garantía."]],
    [["Can I commission a panel with just an idea?",
      "Yes. You can come with only an idea, or even a feeling. From there I take care of the concept, the sketches, the calculations and the whole making."],
     ["How large can it be?",
      "Being modular, the panel can be small or cover an entire wall. It is made in parts in the studio and assembled in your home."],
     ["Is it suitable for a terrace or an exterior?",
      "Yes. Glazed ceramic withstands sun, damp and cold; it is a lasting material for indoors and outdoors, with warranty."]],
    [["Можно ли заказать панно только с идеей?",
      "Да. Можно прийти только с идеей или даже с ощущением. Дальше я беру на себя концепцию, эскизы, расчёты и всё исполнение."],
     ["Какого размера оно может быть?",
      "Панно модульное, поэтому может быть небольшим или занимать всю стену. Оно изготавливается по частям в студии и собирается у вас дома."],
     ["Подойдёт ли для террасы или улицы?",
      "Да. Глазурованная керамика выдерживает солнце, влагу и холод; это долговечный материал для интерьера и экстерьера, с гарантией."]]),
  "related": ["murales-ceramicos", "panel-montanas", "decoracion-espacios"],
})

# ---------------------------------------- SERVICE: vajilla para restaurantes
pages.append({
  "id": "vajilla-restaurantes", "kind": "service", "parent": "servicios", "img": "SRC_CASE3",
  "serviceType": "Bespoke artistic tableware",
  "path": tri("servicios/vajilla-artistica-para-restaurantes",
              "en/services/artistic-tableware-for-restaurants",
              "ru/uslugi/avtorskaya-posuda-dlya-restoranov"),
  "crumb": tri("Vajilla para restaurantes", "Tableware for restaurants", "Посуда для ресторанов"),
  "card": tri("Colecciones de vajilla de autor hechas a mano para restaurantes y hostelería.",
              "Handmade author's tableware collections for restaurants and hospitality.",
              "Авторские коллекции посуды ручной работы для ресторанов и HoReCa."),
  "h1": tri("Vajilla artística a medida para restaurantes",
            "Bespoke artistic tableware for restaurants",
            "Авторская посуда на заказ для ресторанов"),
  "title": tri("Vajilla artística a medida para restaurantes | Inga Burina",
               "Bespoke artistic tableware for restaurants | Inga Burina",
               "Авторская посуда на заказ для ресторанов | Инга Бурина"),
  "desc": tri("Colecciones de vajilla cerámica de autor, hechas a mano, para restaurantes y hostelería en Castellón y Valencia. Piezas de servicio a medida para tu carta.",
              "Handmade author's ceramic tableware collections for restaurants and hospitality in Castellón and Valencia. Bespoke serving pieces for your menu.",
              "Авторские коллекции керамической посуды ручной работы для ресторанов и HoReCa в Castellón и Valencia. Предметы сервировки на заказ под вашу кухню."),
  "img_alt": tri("Fuente cerámica de autor para marisco creada para el restaurante Boca Pez",
                 "Author's ceramic seafood platter made for Boca Pez restaurant",
                 "Авторское керамическое блюдо для морепродуктов, созданное для ресторана Boca Pez"),
  "snippet": tri("Desarrollo colecciones de vajilla de autor, hechas a mano, para restaurantes: platos, fuentes de marisco y objetos de servicio pensados para tu carta y tu marca. Cada pieza es un lienzo donde se encuentran mi visión y la intención del chef.",
                 "I develop handmade author's tableware collections for restaurants: plates, seafood platters and serving objects designed for your menu and your brand. Each piece is a canvas where my vision meets the chef's intention.",
                 "Разрабатываю авторские коллекции посуды ручной работы для ресторанов: тарелки, блюда для морепродуктов и предметы сервировки под вашу кухню и бренд. Каждый предмет — холст, где встречаются моё видение и замысел шефа."),
  "intro": tri_list(
    ["Una colección de vajilla a medida convierte el emplatado en parte de la identidad del restaurante. No son piezas de catálogo: se diseñan con el chef, a partir del tipo de cocina, los productos y el carácter del local.",
     "Creo cerámica que se convierte en una prolongación de la cocina de autor. Formas de servicio para marisco, platos escultóricos, series que los clientes fotografían. Todo hecho y pintado a mano, con materiales certificados aptos para uso alimentario."],
    ["A bespoke tableware collection turns plating into part of the restaurant's identity. These are not catalogue pieces: they are designed with the chef, from the type of cuisine, the produce and the character of the venue.",
     "I make ceramics that become an extension of the chef's cuisine. Seafood serving forms, sculptural plates, series that guests photograph. All made and painted by hand, with certified, food-safe materials."],
    ["Коллекция посуды на заказ делает подачу частью айдентики ресторана. Это не каталожные предметы: они разрабатываются вместе с шефом, исходя из типа кухни, продуктов и характера заведения.",
     "Я создаю керамику, которая становится продолжением авторской кухни. Формы для подачи морепродуктов, скульптурные тарелки, серии, которые гости фотографируют. Всё сделано и расписано вручную, из сертифицированных материалов, пригодных для пищи."]),
  "includes": tri_list(
    ["Concepto de colección con el chef y la marca",
     "Diseño de formas y decoración a medida",
     "Piezas modeladas y pintadas a mano, esmaltadas a fuego",
     "Materiales certificados, aptos para uso alimentario",
     "Series coherentes: platos, fuentes, objetos de servicio",
     "Producción por lotes y reposiciones"],
    ["Collection concept with the chef and the brand",
     "Bespoke form and decoration design",
     "Pieces hand-modelled and painted, kiln-fired",
     "Certified, food-safe materials",
     "Coherent series: plates, platters, serving objects",
     "Batch production and re-orders"],
    ["Концепция коллекции вместе с шефом и брендом",
     "Дизайн форм и декора на заказ",
     "Предметы, вылепленные и расписанные вручную, обожжённые в печи",
     "Сертифицированные материалы, пригодные для пищи",
     "Согласованные серии: тарелки, блюда, предметы сервировки",
     "Производство партиями и дозаказы"]),
  "price": tri("Precio por colección, según formas, cantidad y decoración; se define tras una primera conversación. Plazos de 1 mes a varios según el volumen de la serie.",
               "Priced per collection, based on forms, quantity and decoration; defined after a first conversation. Timelines from 1 month to several depending on the size of the series.",
               "Цена за коллекцию — в зависимости от форм, количества и декора; определяется после первого разговора. Сроки от 1 месяца до нескольких в зависимости от объёма серии."),
  "gallery": [
    {"img": "SRC_WARE_FISH", "alt": tri("Fuentes cerámicas en forma de pez para servir marisco",
                                         "Fish-shaped ceramic platters for serving seafood",
                                         "Керамические блюда в форме рыбы для подачи морепродуктов")},
    {"img": "SRC_WARE_TURQ", "alt": tri("Fuentes cerámicas turquesa en forma de pez con una estrella de mar",
                                         "Turquoise fish-shaped ceramic platters with a starfish",
                                         "Бирюзовые керамические блюда в форме рыбы с морской звездой")},
    {"img": "SRC_WARE_BULL", "alt": tri("Taza cerámica en forma de cabeza de toro servida en un restaurante",
                                         "Bull's-head ceramic cup served in a restaurant",
                                         "Керамическая чашка в форме головы быка, поданная в ресторане")},
    {"img": "SRC_WARE_MOON", "alt": tri("Plato cerámico decorativo con luna y olas",
                                         "Decorative ceramic plate with a moon and waves",
                                         "Декоративная керамическая тарелка с луной и волнами")},
  ],
  "faq": tri_list(
    [["¿Cuál es el pedido mínimo?",
      "Trabajo tanto colecciones completas de restaurante como series cortas. Lo definimos según tu carta y tu ritmo de servicio; también hago reposiciones de piezas."],
     ["¿La vajilla es apta para uso diario en hostelería?",
      "Sí. Uso materiales cerámicos certificados, aptos para uso alimentario. Las piezas se diseñan para el servicio real, no solo para la foto."],
     ["¿Podéis crear piezas ligadas a nuestra marca?",
      "Sí. Puedo incorporar el concepto, los colores o un motivo del restaurante, como se hizo con la vajilla de marisco del restaurante Boca Pez."]],
    [["What is the minimum order?",
      "I take on both full restaurant collections and short series. We define it around your menu and service rhythm; I also make re-orders of pieces."],
     ["Is the tableware suitable for daily hospitality use?",
      "Yes. I use certified, food-safe ceramic materials. Pieces are designed for real service, not just for the photo."],
     ["Can you create pieces tied to our brand?",
      "Yes. I can build in the concept, the colours or a motif of the restaurant, as was done with the seafood tableware for Boca Pez restaurant."]],
    [["Какой минимальный заказ?",
      "Беру как полные ресторанные коллекции, так и короткие серии. Определяем под вашу карту и ритм сервиса; делаю и дозаказы предметов."],
     ["Подходит ли посуда для ежедневного использования в HoReCa?",
      "Да. Использую сертифицированные керамические материалы, пригодные для пищи. Предметы рассчитаны на реальный сервис, а не только на фото."],
     ["Можете создать предметы под наш бренд?",
      "Да. Могу заложить концепцию, цвета или мотив ресторана — как это было сделано с посудой для морепродуктов ресторана Boca Pez."]]),
  "related": ["vajilla-boca-pez", "murales-ceramicos", "decoracion-espacios"],
})

# ------------------------------------------- SERVICE: decoración de espacios
pages.append({
  "id": "decoracion-espacios", "kind": "service", "parent": "servicios", "img": "SRC_DECOR",
  "serviceType": "Ceramic decoration of spaces",
  "path": tri("servicios/decoracion-ceramica-de-espacios",
              "en/services/ceramic-decoration-of-spaces",
              "ru/uslugi/keramicheskiy-dekor-prostranstv"),
  "crumb": tri("Decoración de espacios", "Decoration of spaces", "Декор пространств"),
  "card": tri("Mosaico, chimeneas, cocinas, fachadas y objetos: decoración cerámica integral.",
              "Mosaic, fireplaces, kitchens, façades and objects: complete ceramic decoration.",
              "Мозаика, камины, кухни, фасады и объекты: комплексный керамический декор."),
  "h1": tri("Decoración cerámica de espacios y arquitectura",
            "Ceramic decoration of spaces and architecture",
            "Керамический декор пространств и архитектуры"),
  "title": tri("Decoración cerámica de espacios y arquitectura | Inga Burina",
               "Ceramic decoration of spaces and architecture | Inga Burina",
               "Керамический декор пространств и архитектуры | Инга Бурина"),
  "desc": tri("Decoración cerámica y mosaico (trencadís) a medida para chimeneas, cocinas, fachadas y jardines en Benicàssim y Castellón. Del boceto al montaje.",
              "Bespoke ceramic decoration and mosaic (trencadís) for fireplaces, kitchens, façades and gardens in Benicàssim and Castellón. From sketch to install.",
              "Керамический декор и мозаика (тренкадис) на заказ для каминов, кухонь, фасадов и садов в Benicàssim и Castellón. От эскиза до монтажа."),
  "img_alt": tri("Objeto decorativo de mosaico (trencadís) para un jardín, en la estética de Gaudí",
                 "Decorative mosaic (trencadís) garden object, in Gaudí's aesthetic",
                 "Декоративный объект из мозаики (тренкадис) для сада в эстетике Гауди"),
  "snippet": tri("Cuando un espacio pide más que una pieza, hago decoración cerámica integral: mosaico en la estética de Gaudí, cerámica para chimeneas, cocinas y fachadas, muebles pintados y objetos de jardín. Superficies y objetos artísticos que dan carácter a toda una casa o un local.",
                 "When a space asks for more than a single piece, I create complete ceramic decoration: mosaic in Gaudí's aesthetic, ceramics for fireplaces, kitchens and façades, painted furniture and garden objects. Artistic surfaces and objects that give character to a whole home or venue.",
                 "Когда пространству нужна не одна вещь, я делаю комплексный керамический декор: мозаику в эстетике Гауди, керамику для каминов, кухонь и фасадов, расписную мебель и садовые объекты. Художественные поверхности и объекты, задающие характер всему дому или заведению."),
  "intro": tri_list(
    ["Además de murales, paneles y vajilla, trabajo el espacio como un todo. La cerámica y el mosaico pueden vestir una chimenea, una cocina, una barra, una fachada o una estructura de jardín, y unir todo el ambiente con un mismo lenguaje.",
     "Uso el trencadís — mosaico de azulejo troceado y espejo en la tradición de Gaudí — para superficies y objetos de gran fuerza visual, y la rospintura sobre madera para muebles convertidos en piezas de autor. La cerámica es un material perdurable, apto para interior y exterior, con garantía."],
    ["Beyond murals, panels and tableware, I work the space as a whole. Ceramic and mosaic can dress a fireplace, a kitchen, a bar, a façade or a garden structure, and tie the whole atmosphere together with a single language.",
     "I use trencadís — broken-tile and mirror mosaic in Gaudí's tradition — for surfaces and objects of strong visual power, and painting on wood for furniture turned into authored pieces. Ceramic is a lasting material, suitable indoors and outdoors, with warranty."],
    ["Помимо муралов, панно и посуды, я работаю с пространством как с целым. Керамика и мозаика могут одеть камин, кухню, барную стойку, фасад или садовую структуру и связать всю атмосферу единым языком.",
     "Использую тренкадис — мозаику из битой плитки и зеркала в традиции Гауди — для поверхностей и объектов большой визуальной силы, и роспись по дереву для мебели, превращённой в авторские вещи. Керамика — долговечный материал для интерьера и экстерьера, с гарантией."]),
  "includes": tri_list(
    ["Mosaico y trencadís para superficies y objetos",
     "Cerámica para chimeneas, cocinas y barbacoas",
     "Decoración de fachadas y elementos de jardín",
     "Muebles y objetos pintados a mano",
     "Concepto integral coordinado con arquitecto o interiorista",
     "Producción e instalación con equipo técnico"],
    ["Mosaic and trencadís for surfaces and objects",
     "Ceramics for fireplaces, kitchens and barbecues",
     "Façade decoration and garden elements",
     "Hand-painted furniture and objects",
     "An integral concept coordinated with architect or interior designer",
     "Production and installation with a technical team"],
    ["Мозаика и тренкадис для поверхностей и объектов",
     "Керамика для каминов, кухонь и барбекю",
     "Декор фасадов и садовых элементов",
     "Расписанные вручную мебель и объекты",
     "Комплексная концепция вместе с архитектором или дизайнером",
     "Производство и монтаж с технической командой"]),
  "price": tri("Presupuesto a medida según superficie, técnica y materiales; obra artística desde 200 €/m². Materiales aparte. Bocetos 150–300 €.",
               "Bespoke budget based on surface, technique and materials; artwork from 200 €/m². Materials separate. Sketches 150–300 €.",
               "Смета индивидуально — в зависимости от площади, техники и материалов; художественная работа от 200 €/м². Материалы отдельно. Эскизы 150–300 €."),
  "gallery": [
    {"img": "SRC_WARE_ROOSTER", "alt": tri("Escultura cerámica de gallo con esmalte rojo como objeto decorativo",
                                            "Red-glazed ceramic rooster sculpture as a decorative object",
                                            "Керамическая скульптура петуха с красной глазурью как декоративный объект")},
    {"img": "SRC_GORY_SUCC", "alt": tri("Superficie cerámica con suculentas para la decoración de un espacio",
                                         "Ceramic surface with succulents for the decoration of a space",
                                         "Керамическая поверхность с суккулентами для декора пространства")},
    {"img": "SRC_PROCESS2", "alt": tri("Inga Burina pintando con pincel en el taller",
                                        "Inga Burina painting with a brush in the workshop",
                                        "Инга Бурина расписывает кистью в мастерской")},
  ],
  "faq": tri_list(
    [["¿Trabajáis en obra nueva y en reformas?",
      "En ambas. Puedo entrar en la fase de planificación con el arquitecto o crear una atmósfera nueva en un espacio ya terminado."],
     ["¿Y en trabajos en altura o de gran formato?",
      "Sí, con equipo. Yo aporto el concepto y los elementos clave y dirijo la realización; el montaje en altura lo hace un equipo técnico (electricistas, ingeniero, alicatadores)."],
     ["¿La decoración exterior aguanta el clima?",
      "Sí. La cerámica y el mosaico esmaltados son perdurables para exterior — fachadas, jardines, barbacoas — con garantía."]],
    [["Do you work on new builds and on renovations?",
      "Both. I can join at the planning stage with the architect or create a new atmosphere in an already finished space."],
     ["What about work at height or large formats?",
      "Yes, with a team. I provide the concept and the key elements and direct the making; installation at height is done by a technical team (electricians, engineer, tilers)."],
     ["Does outdoor decoration withstand the climate?",
      "Yes. Glazed ceramic and mosaic are durable outdoors — façades, gardens, barbecues — with warranty."]],
    [["Работаете ли в новостройке и на ремонте?",
      "И там, и там. Могу подключиться на стадии планирования с архитектором или создать новую атмосферу в уже готовом пространстве."],
     ["А работы на высоте и большие форматы?",
      "Да, с командой. Я даю концепцию и ключевые элементы и руковожу исполнением; монтаж на высоте выполняет техническая команда (электрики, инженер, плиточники)."],
     ["Выдерживает ли наружный декор климат?",
      "Да. Глазурованная керамика и мозаика долговечны снаружи — фасады, сады, барбекю — с гарантией."]]),
  "related": ["murales-ceramicos", "paneles-vivienda", "vajilla-restaurantes"],
})

# ---------------------------------------------- PROJECT: panel montañas
pages.append({
  "id": "panel-montanas", "kind": "project", "parent": "proyectos", "img": "SRC_GORY_ROOM",
  "path": tri("proyectos/panel-ceramico-montanas-castellon",
              "en/projects/ceramic-panel-mountains-castellon",
              "ru/proekty/keramicheskoe-panno-gory-kastellon"),
  "crumb": tri("Panel «Donde las montañas tocan el cielo»",
               "Panel “Where the mountains touch the sky”",
               "Панно «Там, где горы касаются неба»"),
  "card": tri("Panel cerámico a medida para una vivienda privada en la costa de Castellón.",
              "Custom ceramic panel for a private home on the Castellón coast.",
              "Керамическое панно на заказ для частного дома на побережье Castellón."),
  "h1": tri("Donde las montañas tocan el cielo",
            "Where the mountains touch the sky",
            "Там, где горы касаются неба"),
  "title": tri("Panel cerámico «Donde las montañas tocan el cielo» · casa privada, Castellón | Inga Burina",
               "Ceramic panel “Where the mountains touch the sky” · private home, Castellón | Inga Burina",
               "Керамическое панно «Там, где горы касаются неба» · частный дом, Castellón | Инга Бурина"),
  "desc": tri("Caso: panel cerámico a medida para una vivienda en la costa de Castellón — costa rocosa con agaves y una abubilla al atardecer, cerámica pintada a mano.",
              "Case study: a custom ceramic panel for a home on the Castellón coast — rocky coast with agaves and a hoopoe at dusk, in hand-painted ceramic.",
              "Кейс: керамическое панно на заказ для дома на побережье Castellón — скалистый берег с агавами и удод на закате, расписная керамика."),
  "meta_line": tri("Panel cerámico a medida · vivienda privada · costa de Castellón · 2025",
                   "Custom ceramic panel · private home · Castellón coast · 2025",
                   "Керамическое панно на заказ · частный дом · побережье Castellón · 2025"),
  "img_alt": tri("Panel cerámico con vistas al mar instalado en la terraza de una vivienda privada",
                 "Ceramic panel with sea views installed on a private home's terrace",
                 "Керамическое панно с видом на море, установленное на террасе частного дома"),
  "snippet": tri("Un panel cerámico para una casa junto al mar: la costa mediterránea rocosa con suculentas y agaves, y una abubilla en una rama de pino sobre el agua al atardecer. La naturaleza de la región llevada a la pared — un panel en el que la naturaleza habla en voz baja.",
                 "A ceramic panel for a house by the sea: the rocky Mediterranean coast with succulents and agaves, and a hoopoe on a pine branch above the water at dusk. The region's nature brought to the wall — a panel in which nature speaks softly.",
                 "Керамическое панно для дома у моря: скалистый средиземноморский берег с суккулентами и агавами и удод на ветке сосны над водой на закате. Природа региона, перенесённая на стену, — панно, в котором природа говорит вполголоса."),
  "story_title": tri("La idea", "The idea", "Идея"),
  "story": tri_list(
    ["Los propietarios querían llevar a casa el paisaje que veían cada día: las rocas de la costa, las suculentas que crecen entre ellas, la luz cálida del atardecer sobre el mar. En lugar de un cuadro, propuse un panel cerámico integrado en la terraza, que forma parte de la arquitectura y resiste el aire salino del exterior.",
     "El panel se pintó y esmaltó a mano y se produjo por módulos en el estudio, para montarlo después in situ. La escena reúne los agaves, la costa rocosa y una abubilla — el ave que trae el primer color del día — como guardiana del rincón.",
     "«Donde las montañas tocan el cielo, y las suculentas crecen como sueños, en la pared floreció el silencio.» El panel es tan decorativo como natural: un fragmento de la costa de Castellón que ahora vive dentro de la casa."],
    ["The owners wanted to bring home the landscape they saw every day: the coastal rocks, the succulents growing among them, the warm evening light over the sea. Instead of a picture, I proposed a ceramic panel built into the terrace, part of the architecture and resistant to the salty outdoor air.",
     "The panel was hand-painted and glazed and produced in modules in the studio, to be installed on site afterwards. The scene brings together the agaves, the rocky coast and a hoopoe — the bird that carries the first colour of the day — as the guardian of the corner.",
     "“Where the mountains touch the sky, and the succulents grow like dreams, silence blossomed on the wall.” The panel is as decorative as it is natural: a fragment of the Castellón coast that now lives inside the house."],
    ["Хозяева хотели принести домой пейзаж, который видели каждый день: прибрежные скалы, суккуленты, растущие между ними, тёплый вечерний свет над морем. Вместо картины я предложила керамическое панно, встроенное в террасу, — оно становится частью архитектуры и выдерживает солёный наружный воздух.",
     "Панно расписано и покрыто глазурью вручную и изготовлено модулями в студии, чтобы затем смонтировать его на месте. В сцене сходятся агавы, скалистый берег и удод — птица, приносящая первый цвет дня, — как хранитель этого уголка.",
     "«Там, где горы касаются неба, а суккуленты растут, как сны, на стене расцвела тишина.» Панно настолько же декоративно, насколько природно: фрагмент побережья Castellón, который теперь живёт внутри дома."]),
  "gallery": [
    {"img": "SRC_GORY_ARTIST", "alt": tri("Inga Burina junto al panel cerámico «Donde las montañas tocan el cielo»",
                                           "Inga Burina beside the ceramic panel “Where the mountains touch the sky”",
                                           "Инга Бурина рядом с керамическим панно «Там, где горы касаются неба»")},
    {"img": "SRC_GORY_SUCC", "alt": tri("Detalle del panel: suculentas y agaves de la costa mediterránea",
                                         "Panel detail: succulents and agaves of the Mediterranean coast",
                                         "Фрагмент панно: суккуленты и агавы средиземноморского берега")},
    {"img": "SRC_GORY_BIRD", "alt": tri("Detalle del panel: abubilla en una rama de pino sobre el mar al atardecer",
                                         "Panel detail: hoopoe on a pine branch above the sea at dusk",
                                         "Фрагмент панно: удод на ветке сосны над морем на закате")},
  ],
  "details_title": tri("Ficha del proyecto", "Project details", "О проекте"),
  "details": tri_list(
    [["Tipo", "Panel cerámico a medida"], ["Cliente", "Vivienda privada"],
     ["Lugar", "Costa de Castellón, España"], ["Año", "2025"],
     ["Material", "Azulejo cerámico pintado a mano, esmaltes"],
     ["Técnica", "Pintura a mano, esmaltado a fuego, montaje modular"],
     ["Uso", "Interior y exterior (terraza)"]],
    [["Type", "Custom ceramic panel"], ["Client", "Private home"],
     ["Location", "Castellón coast, Spain"], ["Year", "2025"],
     ["Material", "Hand-painted ceramic tile, glazes"],
     ["Technique", "Hand painting, kiln firing, modular installation"],
     ["Use", "Indoor and outdoor (terrace)"]],
    [["Тип", "Керамическое панно на заказ"], ["Клиент", "Частный дом"],
     ["Место", "Побережье Castellón, Испания"], ["Год", "2025"],
     ["Материал", "Расписная керамическая плитка, глазури"],
     ["Техника", "Ручная роспись, обжиг, модульный монтаж"],
     ["Использование", "Интерьер и экстерьер (терраса)"]]),
  "artwork": {"name": "Donde las montañas tocan el cielo", "artform": "Ceramic panel",
              "artMedium": "Hand-painted ceramic tile", "material": "Ceramic tile",
              "dateCreated": "2025", "location": "Castellón, España"},
  "cta": tri("Encargar un panel", "Commission a panel", "Заказать панно"),
  "related": ["paneles-vivienda", "murales-ceramicos"],
})

# ---------------------------------------------- PROJECT: mural Habanero
pages.append({
  "id": "mural-habanero", "kind": "project", "parent": "proyectos", "img": "SRC_CASE2",
  "path": tri("proyectos/mural-selva-restaurante-habanero",
              "en/projects/jungle-mural-habanero-restaurant",
              "ru/proekty/mural-dzhungli-restoran-habanero"),
  "crumb": tri("Mural «Selva» · Habanero", "Jungle mural · Habanero", "Мурал «Джунгли» · Habanero"),
  "card": tri("Mural de selva en azulejo pintado a mano para el restaurante Habanero, Benicàssim.",
              "Hand-painted tile jungle mural for Habanero restaurant, Benicàssim.",
              "Мурал «джунгли» из расписной плитки для ресторана Habanero, Benicàssim."),
  "h1": tri("Una selva para el restaurante Habanero",
            "A jungle for Habanero restaurant",
            "Джунгли для ресторана Habanero"),
  "title": tri("Mural cerámico «Selva» · restaurante Habanero, Benicàssim | Inga Burina",
               "Ceramic jungle mural · Habanero restaurant, Benicàssim | Inga Burina",
               "Керамический мурал «Джунгли» · ресторан Habanero, Benicàssim | Инга Бурина"),
  "desc": tri("Caso: mural de selva tropical para el restaurante Habanero en Benicàssim — pintura mural y azulejo cerámico pintado a mano, ligado a la marca del local.",
              "Case study: a tropical jungle mural for Habanero restaurant in Benicàssim — wall painting and hand-painted ceramic tile, tied to the venue's brand.",
              "Кейс: мурал тропических джунглей для ресторана Habanero в Benicàssim — настенная роспись и расписная керамическая плитка, под бренд заведения."),
  "meta_line": tri("Mural + azulejo cerámico · restaurante Habanero · Benicàssim · 2020",
                   "Mural + ceramic tile · Habanero restaurant · Benicàssim · 2020",
                   "Мурал + керамическая плитка · ресторан Habanero · Benicàssim · 2020"),
  "img_alt": tri("Mural de selva en azulejo cerámico pintado a mano en el restaurante Habanero, Benicàssim",
                 "Hand-painted ceramic tile jungle mural at Habanero restaurant, Benicàssim",
                 "Мурал «джунгли» из расписной керамической плитки в ресторане Habanero, Benicàssim"),
  "snippet": tri("Una pared del restaurante convertida en selva tropical: pintura mural y azulejo cerámico pintado a mano — tucanes, monos, lianas y follaje. La atmósfera nace del propio concepto del local, Habanero, en una adaptación de autor a la marca.",
                 "A restaurant wall turned into a tropical jungle: wall painting and hand-painted ceramic tile — toucans, monkeys, vines and foliage. The atmosphere grows from the venue's own concept, Habanero, in an authored adaptation to the brand.",
                 "Стена ресторана, превращённая в тропические джунгли: настенная роспись и расписная керамическая плитка — туканы, обезьяны, лианы и листва. Атмосфера рождается из самой концепции заведения, Habanero, в авторской адаптации под бренд."),
  "story_title": tri("La idea", "The idea", "Идея"),
  "story": tri_list(
    ["Habanero quería que el local fuese, en sí mismo, un viaje a los trópicos. Partiendo de ese concepto, llevé la selva a las paredes combinando dos técnicas: la pintura mural para la escena de fondo y el azulejo cerámico pintado a mano para los detalles con textura y brillo.",
     "Pinté y esmalté la cerámica por una retícula sobre la pared — un trabajo lento, pieza a pieza, para que la plantas, las aves y los monos ganaran profundidad. La cerámica aporta relieve y resistencia; la pintura, amplitud y continuidad de la escena.",
     "El resultado es un espacio en el que cada rincón es una parte de la jungla. Es un ejemplo directo de cómo un mural cerámico puede reforzar la identidad de un restaurante y convertirse en su punto de atracción."],
    ["Habanero wanted the venue itself to be a trip to the tropics. Starting from that concept, I brought the jungle onto the walls by combining two techniques: wall painting for the background scene and hand-painted ceramic tile for the details with texture and shine.",
     "I painted and glazed the ceramic on a grid on the wall — slow work, piece by piece, so the plants, the birds and the monkeys gained depth. Ceramic adds relief and durability; painting adds breadth and continuity to the scene.",
     "The result is a space where every corner is a part of the jungle. It is a direct example of how a ceramic mural can reinforce a restaurant's identity and become its focal point."],
    ["В Habanero хотели, чтобы само заведение было путешествием в тропики. Отталкиваясь от этой концепции, я перенесла джунгли на стены, соединив две техники: настенную роспись для фоновой сцены и расписную керамическую плитку для деталей — с фактурой и блеском.",
     "Керамику я расписывала и глазуровала по сетке прямо на стене — медленная работа, плитка за плиткой, чтобы растения, птицы и обезьяны обрели глубину. Керамика даёт рельеф и стойкость, роспись — широту и непрерывность сцены.",
     "В результате получилось пространство, где каждый уголок — часть джунглей. Это наглядный пример того, как керамический мурал может усилить айдентику ресторана и стать его точкой притяжения."]),
  "gallery": [
    {"img": "SRC_FEATURE", "alt": tri("Tríptico cerámico de selva con monos y aves tropicales para Habanero",
                                       "Ceramic jungle triptych with monkeys and tropical birds for Habanero",
                                       "Керамический триптих «джунгли» с обезьянами и тропическими птицами для Habanero")},
    {"img": "SRC_PROCESS", "alt": tri("Inga Burina pintando a mano el azulejo cerámico del mural",
                                       "Inga Burina hand-painting the mural's ceramic tile",
                                       "Инга Бурина расписывает вручную керамическую плитку мурала")},
    {"img": "SRC_PROCESS2", "alt": tri("Detalle del proceso: pincel y esmaltes sobre azulejo cerámico",
                                        "Process detail: brush and glazes on ceramic tile",
                                        "Деталь процесса: кисть и глазури на керамической плитке")},
  ],
  "details_title": tri("Ficha del proyecto", "Project details", "О проекте"),
  "details": tri_list(
    [["Tipo", "Mural cerámico + pintura mural"], ["Cliente", "Restaurante Habanero"],
     ["Lugar", "Benicàssim, Castellón, España"], ["Año", "2020"],
     ["Material", "Azulejo cerámico pintado a mano, pintura, esmaltes"],
     ["Técnica", "Pintura mural y cerámica pintada a mano sobre retícula"],
     ["Tema", "Selva tropical ligada a la marca"]],
    [["Type", "Ceramic mural + wall painting"], ["Client", "Habanero restaurant"],
     ["Location", "Benicàssim, Castellón, Spain"], ["Year", "2020"],
     ["Material", "Hand-painted ceramic tile, paint, glazes"],
     ["Technique", "Wall painting and hand-painted ceramic on a grid"],
     ["Theme", "Tropical jungle tied to the brand"]],
    [["Тип", "Керамический мурал + настенная роспись"], ["Клиент", "Ресторан Habanero"],
     ["Место", "Benicàssim, Castellón, Испания"], ["Год", "2020"],
     ["Материал", "Расписная керамическая плитка, краска, глазури"],
     ["Техника", "Настенная роспись и ручная роспись керамики по сетке"],
     ["Тема", "Тропические джунгли, связанные с брендом"]]),
  "artwork": {"name": "Tríptico Selva · Habanero", "artform": "Ceramic mural",
              "artMedium": "Hand-painted ceramic tile", "material": "Ceramic tile",
              "dateCreated": "2020", "location": "Benicàssim, Castellón, España"},
  "cta": tri("Un mural para mi local", "A mural for my venue", "Мурал для моего заведения"),
  "related": ["murales-ceramicos", "vajilla-boca-pez"],
})

# ---------------------------------------------- PROJECT: vajilla Boca Pez
pages.append({
  "id": "vajilla-boca-pez", "kind": "project", "parent": "proyectos", "img": "SRC_CASE3",
  "path": tri("proyectos/vajilla-restaurante-boca-pez",
              "en/projects/tableware-boca-pez-restaurant",
              "ru/proekty/posuda-restoran-boca-pez"),
  "crumb": tri("Vajilla · Boca Pez", "Tableware · Boca Pez", "Посуда · Boca Pez"),
  "card": tri("Colección de vajilla de servicio a medida para el restaurante de marisco Boca Pez.",
              "Bespoke serving tableware collection for the seafood restaurant Boca Pez.",
              "Коллекция сервировочной посуды на заказ для рыбного ресторана Boca Pez."),
  "h1": tri("Cerámica creada para el lugar: Boca Pez",
            "Ceramics created for the place: Boca Pez",
            "Керамика, созданная для места: Boca Pez"),
  "title": tri("Vajilla cerámica a medida · restaurante Boca Pez, Benicàssim | Inga Burina",
               "Bespoke ceramic tableware · Boca Pez restaurant, Benicàssim | Inga Burina",
               "Авторская керамическая посуда · ресторан Boca Pez, Benicàssim | Инга Бурина"),
  "desc": tri("Caso: colección de vajilla cerámica de servicio, hecha a mano y a medida, para el restaurante de marisco Boca Pez en Benicàssim.",
              "Case study: a handmade, bespoke ceramic serving tableware collection for the seafood restaurant Boca Pez in Benicàssim.",
              "Кейс: коллекция керамической сервировочной посуды ручной работы на заказ для рыбного ресторана Boca Pez в Benicàssim."),
  "meta_line": tri("Colección de vajilla a medida · restaurante Boca Pez · Benicàssim",
                   "Bespoke tableware collection · Boca Pez restaurant · Benicàssim",
                   "Коллекция посуды на заказ · ресторан Boca Pez · Benicàssim"),
  "img_alt": tri("Fuente cerámica de autor para marisco creada para el restaurante Boca Pez",
                 "Author's ceramic seafood platter created for Boca Pez restaurant",
                 "Авторское керамическое блюдо для морепродуктов, созданное для ресторана Boca Pez"),
  "snippet": tri("Vajilla de servicio desarrollada especialmente para un restaurante de marisco: fuentes y platos de autor, hechos a mano, pensados para la puesta en escena del producto. Un formato de colección a medida para locales y clientes particulares.",
                 "Serving tableware developed specially for a seafood restaurant: author's platters and plates, handmade, designed for the staging of the produce. A bespoke collection format for venues and private clients.",
                 "Сервировочная посуда, разработанная специально для рыбного ресторана: авторские блюда и тарелки ручной работы, продуманные под подачу продукта. Формат коллекции на заказ для заведений и частных клиентов."),
  "story_title": tri("La idea", "The idea", "Идея"),
  "story": tri_list(
    ["Boca Pez es un restaurante de marisco, y su producto pedía una vajilla a su altura. Desarrollé una colección de piezas de servicio — fuentes alargadas, platos con relieve — creadas específicamente para ellos, para que el marisco llegara a la mesa como parte de una escena y no sobre una pieza cualquiera de catálogo.",
     "Cada pieza está modelada y pintada a mano, con materiales cerámicos aptos para uso alimentario. La forma sigue a la función — superficies para compartir, relieves que sujetan el producto — sin renunciar al carácter de autor.",
     "Es el mejor ejemplo de mi formato de «colección a medida»: desarrollo y creación de una serie completa de vajilla para un restaurante, un hotel o una casa, ligada a la cocina y a la identidad del cliente."],
    ["Boca Pez is a seafood restaurant, and its produce called for tableware to match. I developed a collection of serving pieces — long platters, plates with relief — created specifically for them, so the seafood reached the table as part of a scene, not on any catalogue piece.",
     "Each piece is hand-modelled and painted, with food-safe ceramic materials. Form follows function — surfaces for sharing, reliefs that hold the produce — without giving up the authored character.",
     "It is the best example of my “bespoke collection” format: developing and making a full tableware series for a restaurant, a hotel or a home, tied to the client's cuisine and identity."],
    ["Boca Pez — рыбный ресторан, и его продукт требовал посуды под стать. Я разработала коллекцию сервировочных предметов — вытянутые блюда, тарелки с рельефом, — созданных специально для них, чтобы морепродукты попадали на стол как часть сцены, а не на случайный каталожный предмет.",
     "Каждый предмет вылеплен и расписан вручную, из керамических материалов, пригодных для пищи. Форма следует за функцией — поверхности для общей подачи, рельефы, удерживающие продукт, — не теряя авторского характера.",
     "Это лучший пример моего формата «коллекция на заказ»: разработка и создание полной серии посуды для ресторана, отеля или дома, связанной с кухней и айдентикой клиента."]),
  "gallery": [
    {"img": "SRC_BP_BULL", "alt": tri("Taza-fuente cerámica en forma de cabeza de toro con ceviche, para el restaurante Boca Pez",
                                       "Bull's-head ceramic serving cup with ceviche, for Boca Pez restaurant",
                                       "Керамическая чашка-блюдо в форме головы быка с севиче для ресторана Boca Pez")},
    {"img": "SRC_BP_BULLS", "alt": tri("Varias tazas cerámicas de cabeza de toro servidas en la mesa del restaurante Boca Pez",
                                        "Several bull's-head ceramic cups served on the table at Boca Pez restaurant",
                                        "Несколько керамических чашек-«быков» на столе ресторана Boca Pez")},
    {"img": "SRC_BP_FISH", "alt": tri("Fuente cerámica de pescado con ceviche y mango junto a una taza esculpida, Boca Pez",
                                       "Ceramic fish platter with ceviche and mango beside a sculpted mug, Boca Pez",
                                       "Керамическое блюдо-рыба с севиче и манго рядом со скульптурной чашкой, Boca Pez")},
    {"img": "SRC_BP_PLATTER", "alt": tri("Fuente cerámica alargada en forma de pescado para la puesta en escena del marisco, Boca Pez",
                                         "Long fish-shaped ceramic platter for staging seafood, Boca Pez",
                                         "Вытянутое керамическое блюдо в форме рыбы для подачи морепродуктов, Boca Pez")},
  ],
  "details_title": tri("Ficha del proyecto", "Project details", "О проекте"),
  "details": tri_list(
    [["Tipo", "Colección de vajilla de servicio a medida"], ["Cliente", "Restaurante Boca Pez"],
     ["Lugar", "Benicàssim, Castellón, España"],
     ["Material", "Cerámica, esmaltes; apta para uso alimentario"],
     ["Técnica", "Modelado y pintura a mano, esmaltado a fuego"],
     ["Formato", "Serie de servicio (fuentes y platos)"]],
    [["Type", "Bespoke serving tableware collection"], ["Client", "Boca Pez restaurant"],
     ["Location", "Benicàssim, Castellón, Spain"],
     ["Material", "Ceramic, glazes; food-safe"],
     ["Technique", "Hand modelling and painting, kiln firing"],
     ["Format", "Serving series (platters and plates)"]],
    [["Тип", "Коллекция сервировочной посуды на заказ"], ["Клиент", "Ресторан Boca Pez"],
     ["Место", "Benicàssim, Castellón, Испания"],
     ["Материал", "Керамика, глазури; пригодна для пищи"],
     ["Техника", "Ручная лепка и роспись, обжиг"],
     ["Формат", "Сервировочная серия (блюда и тарелки)"]]),
  "artwork": {"name": "Vajilla de servicio · Boca Pez", "artform": "Ceramic tableware",
              "artMedium": "Hand-modelled and painted ceramic", "material": "Ceramic",
              "location": "Benicàssim, Castellón, España"},
  "cta": tri("Una colección para mi restaurante", "A collection for my restaurant", "Коллекция для моего ресторана"),
  "related": ["vajilla-restaurantes", "mural-habanero"],
})

# ---------------------------------------------- PROJECT: Ave de Fuego / Жар-птица
pages.append({
  "id": "ave-fuego", "kind": "project", "parent": "proyectos", "img": "SRC_FB_GARDEN",
  "path": tri("proyectos/ave-de-fuego-barbacoa-ceramica",
              "en/projects/firebird-ceramic-barbecue",
              "ru/proekty/zhar-ptitsa-keramicheskaya-barbekyu"),
  "crumb": tri("«Ave de Fuego» · barbacoa", "“Firebird” · barbecue", "«Жар-птица» · барбекю"),
  "card": tri("Mural cerámico con un ave de fuego sobre una barbacoa de jardín — cerámica para el exterior.",
              "Ceramic mural with a firebird over a garden barbecue — ceramics for the outdoors.",
              "Керамический мурал с жар-птицей на садовом барбекю — керамика для улицы."),
  "h1": tri("«Ave de Fuego»: cerámica sobre una barbacoa de jardín",
            "“Firebird”: ceramics on a garden barbecue",
            "«Жар-птица»: керамика на садовом барбекю"),
  "title": tri("«Ave de Fuego» · mural cerámico sobre barbacoa de jardín | Inga Burina",
               "“Firebird” · ceramic mural on a garden barbecue | Inga Burina",
               "«Жар-птица» · керамический мурал на садовом барбекю | Инга Бурина"),
  "desc": tri("Caso: mural cerámico con un ave de fuego dorada sobre una barbacoa de jardín en Benicàssim — azulejo pintado a mano y mosaico, cerámica para exteriores.",
              "Case study: a ceramic mural with a golden firebird over a garden barbecue in Benicàssim — hand-painted tile and mosaic, ceramics for the outdoors.",
              "Кейс: керамический мурал с золотой жар-птицей на садовом барбекю в Benicàssim — расписная плитка и мозаика, керамика для улицы."),
  "meta_line": tri("Mural cerámico · barbacoa de jardín · exterior · Benicàssim",
                   "Ceramic mural · garden barbecue · exterior · Benicàssim",
                   "Керамический мурал · садовое барбекю · экстерьер · Benicàssim"),
  "img_alt": tri("Barbacoa de jardín revestida de cerámica con un ave de fuego dorada pintada a mano en el frontón",
                 "Garden barbecue clad in ceramic with a hand-painted golden firebird on the gable",
                 "Садовое барбекю, облицованное керамикой, с расписанной вручную золотой жар-птицей на фронтоне"),
  "snippet": tri("Una estructura de barbacoa de jardín convertida en pieza de autor: un ave de fuego dorada — el pájaro de fuego del folclore ruso — preside el frontón en azulejo cerámico pintado a mano, entre bordes florales y mosaico. Es un ejemplo de mi trabajo de cerámica para chimeneas, barbacoas y fachadas, pensado para durar a la intemperie.",
                 "A garden barbecue structure turned into an authored piece: a golden firebird — the fire bird of Russian folklore — presides over the gable in hand-painted ceramic tile, among floral borders and mosaic. It is an example of my work in ceramics for fireplaces, barbecues and façades, made to last outdoors.",
                 "Садовая структура барбекю, превращённая в авторскую вещь: золотая жар-птица — огненная птица русского фольклора — венчает фронтон в расписной керамической плитке, среди цветочных бордюров и мозаики. Это пример моей работы по керамике для каминов, барбекю и фасадов, рассчитанной на улицу."),
  "story_title": tri("La idea", "The idea", "Идея"),
  "story": tri_list(
    ["Un rincón funcional del jardín — la barbacoa — puede ser también el centro artístico del espacio. Sobre esta estructura de exterior llevé un ave de fuego dorada, una figura que trae el folclore ruso al jardín mediterráneo.",
     "El frontón se revistió con azulejo cerámico pintado a mano y esmaltado a fuego; los laterales, con bordes florales y ornamentales, y el conjunto dialoga con elementos de mosaico (trencadís) en las superficies cercanas. La cerámica no solo decora: protege la estructura y resiste el sol, la lluvia y el calor del fuego.",
     "Es la muestra de un servicio concreto — cerámica para chimeneas, cocinas, hornos de barbacoa y fachadas — donde el arte se integra en la arquitectura del hogar y del jardín."],
    ["A functional corner of the garden — the barbecue — can also be the artistic centre of the space. Onto this outdoor structure I brought a golden firebird, a figure that carries Russian folklore into a Mediterranean garden.",
     "The gable was clad in hand-painted, kiln-fired ceramic tile; the sides, with floral and ornamental borders, and the whole talks to mosaic (trencadís) elements on the nearby surfaces. Ceramic does not only decorate: it protects the structure and withstands sun, rain and the heat of the fire.",
     "It is a sample of a concrete service — ceramics for fireplaces, kitchens, barbecue ovens and façades — where art becomes part of the architecture of the home and the garden."],
    ["Функциональный уголок сада — барбекю — может быть и художественным центром пространства. На эту наружную структуру я перенесла золотую жар-птицу — образ, приносящий русский фольклор в средиземноморский сад.",
     "Фронтон облицован расписной керамической плиткой, обожжённой в печи; боковины — цветочными и орнаментальными бордюрами, а всё вместе перекликается с элементами мозаики (тренкадис) на соседних поверхностях. Керамика не только украшает: она защищает структуру и выдерживает солнце, дождь и жар огня.",
     "Это образец конкретной услуги — керамика для каминов, кухонь, печей-барбекю и фасадов, — где искусство становится частью архитектуры дома и сада."]),
  "gallery": [
    {"img": "SRC_FB_BIRD", "alt": tri("Detalle del frontón: ave de fuego dorada pintada a mano sobre azulejo cerámico",
                                       "Gable detail: hand-painted golden firebird on ceramic tile",
                                       "Фрагмент фронтона: расписанная вручную золотая жар-птица на керамической плитке")},
    {"img": "SRC_FB_HEARTH", "alt": tri("Vista frontal de la barbacoa con el ave de fuego y el hogar de fuego",
                                         "Front view of the barbecue with the firebird and the fire hearth",
                                         "Вид спереди на барбекю с жар-птицей и очагом")},
    {"img": "SRC_FB_MOSAIC", "alt": tri("La barbacoa cerámica junto a una mesa de mosaico (trencadís) en el jardín",
                                         "The ceramic barbecue beside a mosaic (trencadís) table in the garden",
                                         "Керамическое барбекю рядом с мозаичным столом (тренкадис) в саду")},
  ],
  "details_title": tri("Ficha del proyecto", "Project details", "О проекте"),
  "details": tri_list(
    [["Tipo", "Mural cerámico sobre estructura de barbacoa"],
     ["Ubicación", "Jardín, Benicàssim, Castellón"],
     ["Material", "Azulejo cerámico pintado a mano, esmaltes, mosaico"],
     ["Técnica", "Pintura a mano, esmaltado a fuego, trencadís"],
     ["Uso", "Exterior (barbacoa de jardín)"],
     ["Tema", "Ave de fuego (folclore ruso) + bordes florales"]],
    [["Type", "Ceramic mural on a barbecue structure"],
     ["Location", "Garden, Benicàssim, Castellón"],
     ["Material", "Hand-painted ceramic tile, glazes, mosaic"],
     ["Technique", "Hand painting, kiln firing, trencadís"],
     ["Use", "Exterior (garden barbecue)"],
     ["Theme", "Firebird (Russian folklore) + floral borders"]],
    [["Тип", "Керамический мурал на структуре барбекю"],
     ["Место", "Сад, Benicàssim, Castellón"],
     ["Материал", "Расписная керамическая плитка, глазури, мозаика"],
     ["Техника", "Ручная роспись, обжиг, тренкадис"],
     ["Использование", "Экстерьер (садовое барбекю)"],
     ["Тема", "Жар-птица (русский фольклор) + цветочные бордюры"]]),
  "artwork": {"name": "Ave de Fuego", "artform": "Ceramic mural",
              "artMedium": "Hand-painted ceramic tile", "material": "Ceramic tile",
              "location": "Benicàssim, Castellón, España"},
  "cta": tri("Cerámica para mi jardín", "Ceramics for my garden", "Керамика для моего сада"),
  "related": ["decoracion-espacios", "murales-ceramicos"],
})

# ---------------------------------------------- PROFILE: sobre Inga
pages.append({
  "id": "sobre-inga", "kind": "profile", "img": "SRC_PORTRAIT",
  "path": tri("sobre-inga-burina", "en/about-inga-burina", "ru/ob-inge-burinoy"),
  "crumb": tri("Sobre Inga Burina", "About Inga Burina", "Об Инге Буриной"),
  "h1": tri("Inga Burina — artista ceramista",
            "Inga Burina — ceramic artist",
            "Инга Бурина — художница-керамист"),
  "title": tri("Sobre Inga Burina — artista ceramista en Benicàssim | IngArt Studio",
               "About Inga Burina — ceramic artist in Benicàssim | IngArt Studio",
               "Об Инге Буриной — художница-керамист в Benicàssim | IngArt Studio"),
  "desc": tri("Inga Burina, artista ruso-española afincada en Benicàssim desde 1997. Cerámica, murales, mosaico y decoración de espacios a medida, del boceto al montaje.",
              "Inga Burina, a Russian-Spanish artist based in Benicàssim since 1997. Bespoke ceramics, murals, mosaic and decoration of spaces, from sketch to install.",
              "Инга Бурина, русско-испанская художница, живёт в Benicàssim с 1997 года. Керамика, муралы, мозаика и декор пространств на заказ, от эскиза до монтажа."),
  "img_alt": tri("Retrato de Inga Burina pintando en su estudio de Benicàssim",
                 "Portrait of Inga Burina painting in her Benicàssim studio",
                 "Портрет Инги Буриной за росписью в её студии в Benicàssim"),
  "snippet": tri("Artista ruso-española afincada en Benicàssim desde 1997. Trabajo en el cruce de la cerámica, la pintura, el mosaico y la decoración de espacios, con un solo fin: crear belleza de maneras distintas — del primer boceto al montaje in situ.",
                 "A Russian-Spanish artist based in Benicàssim since 1997. I work at the crossing of ceramics, painting, mosaic and the decoration of spaces, with a single aim: to create beauty in different ways — from the first sketch to the on-site installation.",
                 "Русско-испанская художница, живу в Benicàssim с 1997 года. Работаю на стыке керамики, живописи, мозаики и декора пространств с одной целью — создавать красоту разными способами, от первого эскиза до монтажа на месте."),
  "paras": tri_list(
    ["Nací en Moscú en 1974 y vivo y trabajo en Benicàssim, en la provincia de Castellón, desde 1997. Me formé en Rusia y en España, y con los años he reunido un abanico amplio de técnicas — cerámica, pintura, mosaico, mural — porque me gusta tener muchas herramientas para crear belleza de maneras distintas.",
     "Mi trabajo actual gira en torno a IngArt Studio: murales y paneles cerámicos a medida, vajilla de autor y decoración de espacios para viviendas, restaurantes y hoteles. Me interesan sobre todo los materiales antiguos, tradicionales y naturales — la arcilla, los esmaltes, la mosaico — por su energía viva y su capacidad de perdurar.",
     "Trabajo el ciclo completo con mis propias manos, del boceto al montaje: la idea, los bocetos, los cálculos, la producción en el estudio y la instalación. Para las obras grandes formo un equipo, pero el concepto y las piezas clave son siempre míos. Mi lenguaje bebe del Mediterráneo, de la naturaleza, del mar y de un imaginario propio, reconocible.",
     "En Benicàssim está también Ingart Art House — taller artístico y galería con eventos, donde además puede organizarse una velada gastronómica con un chef profesional."],
    ["I was born in Moscow in 1974 and have lived and worked in Benicàssim, in the province of Castellón, since 1997. I trained in Russia and Spain, and over the years I have gathered a broad range of techniques — ceramics, painting, mosaic, mural — because I like having many tools to create beauty in different ways.",
     "My current work revolves around IngArt Studio: custom ceramic murals and panels, author's tableware and the decoration of spaces for homes, restaurants and hotels. I am drawn above all to ancient, traditional, natural materials — clay, glazes, mosaic — for their living energy and their ability to last.",
     "I work the full cycle with my own hands, from sketch to installation: the idea, the sketches, the calculations, the production in the studio and the fitting. For large works I form a team, but the concept and the key pieces are always mine. My language draws on the Mediterranean, on nature, on the sea and on a personal, recognisable imagery.",
     "In Benicàssim there is also Ingart Art House — an art workshop and gallery with events, where a gastronomic evening with a professional chef can also be arranged."],
    ["Я родилась в Москве в 1974 году и живу и работаю в Benicàssim, в провинции Castellón, с 1997 года. Училась в России и в Испании и за годы собрала широкий набор техник — керамика, живопись, мозаика, мурал, — потому что мне нравится иметь много инструментов, чтобы создавать красоту разными способами.",
     "Моя нынешняя работа строится вокруг IngArt Studio: керамические муралы и панно на заказ, авторская посуда и декор пространств для домов, ресторанов и отелей. Больше всего меня привлекают древние, традиционные, натуральные материалы — глина, глазури, мозаика — за их живую энергию и способность оставаться надолго.",
     "Весь цикл я делаю собственными руками, от эскиза до монтажа: идея, эскизы, расчёты, производство в студии и установка. Для крупных работ собираю команду, но концепция и ключевые элементы всегда мои. Мой язык питается Средиземноморьем, природой, морем и собственным узнаваемым образным миром.",
     "В Benicàssim есть и Ingart Art House — художественная мастерская и галерея с мероприятиями, где можно организовать и гастрономический вечер с профессиональным поваром."]),
  "gallery": [
    {"img": "SRC_PROCESS", "alt": tri("Inga Burina pintando azulejo cerámico en el estudio",
                                       "Inga Burina painting ceramic tile in the studio",
                                       "Инга Бурина расписывает керамическую плитку в студии")},
    {"img": "SRC_PROCESS2", "alt": tri("Inga Burina pintando con pincel en el taller",
                                        "Inga Burina painting with a brush in the workshop",
                                        "Инга Бурина расписывает кистью в мастерской")},
  ],
  "cta": tri("Hablar de un proyecto", "Talk about a project", "Обсудить проект"),
  "related": ["murales-ceramicos", "vajilla-restaurantes"],
})

# ---------------------------------------------- CLASSES (studio workshop)
pages.append({
  "id": "clases", "kind": "service", "img": "SRC_CLASS_GROUP",
  "serviceType": "Ceramic and decorative art classes",
  "eyebrow": tri("Taller · Benicàssim", "Workshop · Benicàssim", "Мастерская · Benicàssim"),
  "path": tri("clases-de-ceramica", "en/ceramic-classes", "ru/uroki-keramiki"),
  "crumb": tri("Clases de cerámica", "Ceramic classes", "Уроки керамики"),
  "card": tri("Clases de cerámica y arte decorativo en el estudio de Benicàssim.",
              "Ceramic and decorative art classes at the Benicàssim studio.",
              "Уроки керамики и декоративного искусства в студии Benicàssim."),
  "h1": tri("Clases de cerámica y arte decorativo en Benicàssim",
            "Ceramic and decorative art classes in Benicàssim",
            "Уроки керамики и декоративного искусства в Benicàssim"),
  "title": tri("Clases de cerámica y arte decorativo en Benicàssim | IngArt Studio",
               "Ceramic and decorative art classes in Benicàssim | IngArt Studio",
               "Уроки керамики и декоративного искусства в Benicàssim | IngArt Studio"),
  "desc": tri("Clases de cerámica, mosaico, pirografía y pintura con Inga Burina en su estudio de Benicàssim. Para niños y adultos, desde cero. Verano 2026 desde 25 €.",
              "Ceramic, mosaic, pyrography and painting classes with Inga Burina in her Benicàssim studio. For children and adults, from scratch. Summer 2026 from 25 €.",
              "Уроки керамики, мозаики, пирографии и живописи с Ингой Буриной в студии в Benicàssim. Для детей и взрослых, с нуля. Лето 2026 от 25 €."),
  "img_alt": tri("Clase de cerámica al aire libre con niños y adultos en el estudio de Inga Burina, Benicàssim",
                 "Outdoor ceramic class with children and adults at Inga Burina's studio, Benicàssim",
                 "Занятие по керамике на открытом воздухе с детьми и взрослыми в студии Инги Буриной, Benicàssim"),
  "snippet": tri("En mi estudio de Benicàssim, Ingart Art House, imparto clases de cerámica y arte decorativo para niños y adultos, desde cero o con experiencia. Cada persona trabaja su propia pieza — de la idea a la forma cocida — con las mismas técnicas que uso en los encargos.",
                 "At my Benicàssim studio, Ingart Art House, I teach ceramic and decorative art classes for children and adults, from scratch or with experience. Each person works on their own piece — from the idea to the fired form — with the same techniques I use in commissions.",
                 "В моей студии в Benicàssim, Ingart Art House, я веду уроки керамики и декоративного искусства для детей и взрослых — с нуля или с опытом. Каждый работает над своей вещью — от идеи до обожжённой формы — теми же техниками, что я использую в заказах."),
  "intro": tri_list(
    ["El estudio no es solo un taller de producción: también es un lugar para aprender. En grupos pequeños enseño a modelar, pintar y esmaltar cerámica, y a trabajar otras técnicas decorativas, a tu ritmo y según lo que quieras crear.",
     "No hace falta experiencia previa. Empezamos por lo básico — el barro, la forma, el color — y avanzamos hasta que te llevas a casa tu propia pieza, cocida y terminada. También hay clases pensadas para niños."],
    ["The studio is not only a production workshop: it is also a place to learn. In small groups I teach how to model, paint and glaze ceramics, and how to work other decorative techniques, at your own pace and according to what you want to create.",
     "No previous experience is needed. We start from the basics — the clay, the form, the colour — and move on until you take home your own piece, fired and finished. There are also classes designed for children."],
    ["Студия — не только производственная мастерская, но и место, где можно учиться. В маленьких группах я учу лепить, расписывать и глазуровать керамику, а также работать в других декоративных техниках — в вашем ритме и под то, что вы хотите создать.",
     "Опыт не нужен. Начинаем с основ — глина, форма, цвет — и доходим до того, что вы забираете домой свою вещь, обожжённую и завершённую. Есть и занятия для детей."]),
  "includes_title": tri("Qué se puede aprender", "What you can learn", "Чему можно научиться"),
  "includes": tri_list(
    ["Curso de cerámica artística (modelado, torno a mano, pintura y esmalte)",
     "Mosaico y trencadís al estilo mediterráneo",
     "Pirografía y pintura sobre madera",
     "Pintura mural y creación de cuadros",
     "Pintura sobre seda y ropa",
     "Para niños y adultos · desde cero o con experiencia"],
    ["Artistic ceramics course (modelling, hand-building, painting and glazing)",
     "Mosaic and trencadís in the Mediterranean style",
     "Pyrography and painting on wood",
     "Wall painting and picture-making",
     "Painting on silk and clothing",
     "For children and adults · from scratch or with experience"],
    ["Курс художественной керамики (лепка, ручная формовка, роспись и глазурь)",
     "Мозаика и тренкадис в средиземноморском стиле",
     "Пирография и роспись по дереву",
     "Настенная роспись и создание картин",
     "Роспись по шёлку и одежде",
     "Для детей и взрослых · с нуля или с опытом"]),
  "price": tri("Clases de verano 2026 · desde 25 € · en grupos pequeños. Fechas y plazas por WhatsApp.",
               "Summer 2026 classes · from 25 € · in small groups. Dates and places via WhatsApp.",
               "Летние классы 2026 · от 25 € · в маленьких группах. Даты и места — в WhatsApp."),
  "gallery": [
    {"img": "SRC_CLASS_HANDSON", "alt": tri("Un adulto y una niña modelando arcilla juntos en una clase de cerámica al aire libre",
                                             "An adult and a child modelling clay together in an outdoor ceramics class",
                                             "Взрослый и девочка вместе лепят из глины на занятии по керамике на открытом воздухе")},
    {"img": "SRC_CLASS_TEXTURE", "alt": tri("Manos imprimiendo la textura de una hoja natural sobre una placa de arcilla",
                                            "Hands pressing the texture of a natural leaf onto a clay slab",
                                            "Руки оттискивают фактуру натурального листа на глиняной пластине")},
    {"img": "SRC_CLASS_WORKS", "alt": tri("Piezas cerámicas terminadas y esmaltadas hechas por alumnos: taza-zorro, plato con mariposa y pez azul",
                                          "Finished glazed ceramic pieces made by students: a fox cup, a butterfly plate and a blue fish",
                                          "Готовые глазурованные керамические работы учеников: чашка-лиса, тарелка с бабочкой и синяя рыба")},
  ],
  "faq": tri_list(
    [["¿Necesito experiencia previa?",
      "No. Las clases están pensadas para empezar desde cero; también para quien ya tiene práctica y quiere perfeccionar una técnica."],
     ["¿Hay clases para niños?",
      "Sí. Trabajo con niños y con adultos; el enfoque y el ritmo se adaptan a cada grupo."],
     ["¿Cómo me apunto?",
      "Escríbeme por WhatsApp y te digo las fechas, los horarios y las plazas disponibles de la temporada. Los grupos son pequeños."]],
    [["Do I need previous experience?",
      "No. The classes are designed to start from scratch; also for those who already have practice and want to refine a technique."],
     ["Are there classes for children?",
      "Yes. I work with both children and adults; the approach and the pace adapt to each group."],
     ["How do I sign up?",
      "Message me on WhatsApp and I'll tell you the dates, times and places available for the season. Groups are small."]],
    [["Нужен ли опыт?",
      "Нет. Занятия рассчитаны на старт с нуля; подойдут и тем, у кого уже есть практика и кто хочет отточить технику."],
     ["Есть ли занятия для детей?",
      "Да. Работаю и с детьми, и со взрослыми; подход и темп подстраиваются под каждую группу."],
     ["Как записаться?",
      "Напишите мне в WhatsApp — расскажу даты, время и свободные места на сезон. Группы небольшие."]]),
  "cta": tri("Apuntarme a una clase", "Book a class", "Записаться на занятие"),
  "related": ["sobre-inga"],
})

data = {
    "_generated_by": "pages.gen.py — DO NOT edit pages.json by hand; edit pages.gen.py and rebuild",
    "pages": pages,
}
out = pathlib.Path(__file__).with_name("pages.json")
out.write_text(json.dumps(data, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"pages.gen: wrote {out.name} with {len(pages)} pages")
